### ISSUE TITLE
Migrate the DB to Postgresql + Postgis + Docker

### ISSUE THREAD

**Issue by tecoholic** [covid19india/CovidCrowd#53]
This is a long term issue. Right now the database is a SQLite3 DB with SpatiaLite adaptor for the Geographic data and features. The deployment is manual. This needs to be changed to a better DevOps setup.

1. Database needs to be moved to Posgresql with PostGIS layer
2. Then the app and database need to be containerised using docker for easy deployment

**Comment by 83bytes** [comment]
What portion of the deployment-pipeline are we trying to improve with Docker. 
With the number of parts in the deployment workflow, containerizing the entire app might not be a good idea. 

Also, we will have to figure out proper logging because having them inside docker wont make much sense. 

Furthermore, if we do separate the DB into PgSQL then we will need a different pipeline for that. 


in any case, for now, we can create a container can will be easy to deloy with a single line command. 
Is that what you want ?

**Comment by tecoholic** [comment]
The aim would be to have containers handled by docker-compose.

1. GeoDjango app with Python and Gdal
2. Postgresql with postgis
3. A memcahched container for caching

About logging, I will open a fresh issue dedicated to that. Right now we have absolutely no logs and that's a terrible thing.

Finally we don't want multiple pipelines. Just a simple docker-compose orchestration with the containers would be good.

**Comment by uberdeveloper** [comment]
Hi,
Is Google Cloud Big query and other google tools ok for you so that we can reduce the devops considerably once the set up is done correctly

**Comment by 83bytes** [comment]
So i am working on this issue. 

I think it would be a good idea to separate the static files and the wsgi files into different containers. 
Otherwise having nginx and gunicorn in one container wouldn't be ideal. 

Also, please forgive me but i could not understand where the data files are stored. Could you help me with that ?

**Comment by tecoholic** [comment]
Just to clarify, this project is **NOT** the one powering the covid19india.org dashboard. 

The datafiles for this file are present in the `data` folder of the repository and how to import them is documented in README.
