### ISSUE TITLE
Add States and Districts data to app

### ISSUE THREAD

**Issue by tecoholic** [covid19india/CovidCrowd#7]
States and Districts in the input fields across the application should be dropdowns. Since there are only 37 states and union territories, it is already in the code. But the Districts are not. And they need to be dynamic as well, so the user sees only the districts based on what is selected in the State field.

Attaching the data required for it as a CSV
[States and Districts.xlsx](https://github.com/covid19india/CovidCrowd/files/4362589/States.and.Districts.xlsx)

**Comment by tecoholic** [comment]
closed with pull request number 2

**Comment by aadityadar** [comment]
Hi, the excel file that you are using for district names seems to refer to early 2019 district. Acc to https://lgdirectory.gov.in/ there are 729 districts. There are three sources of differences:
- LGD reports 20 districts in J&K (instead of 22; mirpur and muzaffarabad not reported by LGD)
- LGD reports 11 districts in Mizoram (instead of 8; hnahthial,   khawzawl, saitual are three new districts formed in June 2019)
- LGD reports 33 district in Tamil Nadu (instead of 32; kallakurichi  district was formed in november 2019)

Here's the updated list of districts that you could consider using https://isbhydmoh-my.sharepoint.com/:x:/g/personal/aaditya_dar_isb_edu/ET2l0-oTsC5NjGZ98kbiXjEBFM998bmFdJ7NebjaTzfI2A?e=nwFASB
